DROP TABLE IF EXISTS MISSIONS_SKILLS;
DROP TABLE IF EXISTS USERS_LANGUAGES;
DROP TABLE IF EXISTS TYPE_MISSIONS;

DROP TABLE IF EXISTS USERS_MISSIONS;
DROP TABLE IF EXISTS MISSIONS;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS SKILLS;
DROP TABLE IF EXISTS LANGUAGES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS(
  id  SERIAL PRIMARY KEY,
  first_name VARCHAR(125),
  last_name VARCHAR(125),
  mail  VARCHAR(125),
  login VARCHAR(7) NOT NULL,
  position VARCHAR(125),
  experience VARCHAR(20),
  birth_date DATE,
  hobbies VARCHAR(50),
  telephone VARCHAR(10),
  password VARCHAR(125),
  picture VARCHAR(125),
  admin BOOLEAN
);

CREATE TABLE IF NOT EXISTS LANGUAGES(
  id SERIAL PRIMARY KEY,
  label VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTS(
  id SERIAL PRIMARY KEY,
  label VARCHAR(30) NOT NULL,
  domain VARCHAR(20),
  description VARCHAR(125) NOT NULL
);

CREATE TABLE IF NOT EXISTS TYPE_MISSIONS(
  id SERIAL PRIMARY KEY,
  label VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS MISSIONS(
  id SERIAL PRIMARY KEY,
  title VARCHAR(30),
  begin_date DATE,
  end_date DATE,
  client_id INT NOT NULL,
  description VARCHAR,
  type_id INT NOT NULL,
  FOREIGN KEY (type_id) REFERENCES TYPE_MISSIONS(id),
  FOREIGN KEY (client_id) REFERENCES CLIENTS(id)
);

CREATE TABLE IF NOT EXISTS SKILLS(
  id SERIAL PRIMARY KEY,
  label VARCHAR(50) NOT NULL,
  domain VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS MISSIONS_SKILLS(
  missions_id INT NOT NULL,
  skills_id INT NOT NULL,
  FOREIGN KEY (skills_id) REFERENCES SKILLS(id),
  FOREIGN KEY (missions_id) REFERENCES MISSIONS(id)
);

CREATE TABLE IF NOT EXISTS USERS_LANGUAGES(
  user_id INT NOT NULL,
  language_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS(id),
  FOREIGN KEY (language_id) REFERENCES LANGUAGES(id)
);

CREATE TABLE IF NOT EXISTS USERS_MISSIONS(
  user_id INT NOT NULL,
  missions_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS(id),
  FOREIGN KEY (missions_id) REFERENCES MISSIONS(id)
);